### ISSUE TITLE
Projections

### ISSUE THREAD

**Issue by mpaul31** [volak/Aggregates.NET#1]
This project looks very promising! I am new to event sourcing and I am looking through the source to find where the view models are being built from projections. Can you point me to the correct place?

Thanks

**Comment by volak** [comment]
Thanks - 
Configuring projections is a future feature I may or may not implement.  The best way to setup projects in EventStore is via javascript.  I believe there is a C# way to customize projections but I am not familiar with it at all and to my knowledge projections in general are not production ready.

Because we have NSB at our disposal in this project, I went for their way of event sourcing aggregate objects using DDD concepts.  DDD and event sourcing work very well together, you can see an example of building view models in the example project here: https://github.com/volak/DDD.Enterprise.Example/tree/master/Application/ServiceStack/ServiceStack.Accounting/Account/Handlers

Events are raised from aggregates on the domain project, and application type projects subscribe to EventStore and receive events which they use to build their own specialized view models.  In the example above I build 2 view models, a GET type and an INDEX type.  INDEX is a specialized minimal version of the GET information for speedy grid type results
